package telemetry

const (
	AttrServiceName                = "service.name"
	AttrRequestID                  = "request.id"
	AttrTraceID                    = "trace.id"
	AttrSpanID                     = "span.id"
	AttrEnduserID                  = "enduser.id"
	AttrTenantID                   = "tenant.id"
	AttrErrorType                  = "error.type"
	AttrErrorMessage               = "error.message"
	AttrGenAIProviderName          = "gen_ai.provider.name"
	AttrGenAIRequestModel          = "gen_ai.request.model"
	AttrGenAIResponseModel         = "gen_ai.response.model"
	AttrGenAIUsageInputTokens      = "gen_ai.usage.input_tokens"
	AttrGenAIUsageOutputTokens     = "gen_ai.usage.output_tokens"
	AttrGenAIUsageTotalTokens      = "gen_ai.usage.total_tokens"
	AttrHecateAuthRole             = "hecate.auth.role"
	AttrHecateAuthSource           = "hecate.auth.source"
	AttrHecateAuthKeyID            = "hecate.auth.key_id"
	AttrHecatePhase                = "hecate.phase"
	AttrHecateResult               = "hecate.result"
	AttrHecateErrorKind            = "hecate.error.kind"
	AttrHecateProviderKind         = "hecate.provider.kind"
	AttrHecateRouteReason          = "hecate.route.reason"
	AttrHecateCacheHit             = "hecate.cache.hit"
	AttrHecateCacheType            = "hecate.cache.type"
	AttrHecateSemanticStrategy     = "hecate.semantic.strategy"
	AttrHecateSemanticIndexType    = "hecate.semantic.index_type"
	AttrHecateSemanticSimilarity   = "hecate.semantic.similarity"
	AttrHecateCostTotalMicrosUSD   = "hecate.cost.total_micros_usd"
	AttrHecateRetryAttemptCount    = "hecate.retry.attempt_count"
	AttrHecateRetryCount           = "hecate.retry.retry_count"
	AttrHecateFailoverFromProvider = "hecate.failover.from_provider"
	MetricLabelProvider            = "provider"
	MetricLabelProviderKind        = "provider_kind"
	MetricLabelCacheType           = "cache_type"
	MetricLabelStrategy            = "strategy"
	MetricLabelIndexType           = "index_type"
	MetricLabelResult              = "result"
	ResultSuccess                  = "success"
	ResultDenied                   = "denied"
	ResultError                    = "error"
)
