import type { RuntimeConsoleViewModel } from "../app/useRuntimeConsole";

export function createRuntimeConsoleFixture(
  overrides: Partial<RuntimeConsoleViewModel["state"]> = {},
): RuntimeConsoleViewModel["state"] {
  return {
    apiKeyFormID: "",
    apiKeyFormModels: [],
    apiKeyFormName: "",
    apiKeyFormProviders: [],
    apiKeyFormRole: "tenant",
    apiKeyFormSecret: "",
    apiKeyFormTenant: "",
    authToken: "",
    accountSummary: null,
    budget: null,
    budgetActionError: "",
    budgetAmountUsd: "1.00",
    budgetLimitUsd: "5.00",
    activeChatSession: null,
    activeChatSessionID: "",
    chatError: "",
    chatErrorCode: "",
    chatErrorStatus: null,
    chatLoading: false,
    streamingContent: null,
    chatResult: null,
    pendingToolCalls: [],
    chatSessions: [],
    cloudModels: [],
    cloudProviders: [],
    adminConfig: null,
    adminConfigError: "",
    copiedCommand: "",
    error: "",
    health: { status: "ok", time: "2026-04-21T10:00:00Z" },
    healthyCloudProviders: 0,
    healthyLocalProviders: 0,
    healthyProviders: 0,
    loading: false,
    localModels: [],
    localProviderIssues: [],
    localProviders: [],
    message: "Say hello",
    systemPrompt: "",
    model: "gpt-4o-mini",
    modelFilter: "all",
    models: [],
    notice: null,
    session: {
      kind: "anonymous",
      label: "Anonymous",
      capabilities: [],
      isAdmin: false,
      isAuthenticated: false,
      role: "anonymous",
      name: "",
      tenant: "",
      source: "",
      keyID: "",
      allowedProviders: [],
      allowedModels: [],
    },
    providerFilter: "auto",
    providerPresets: [],
    providerScopedModels: [],
    providers: [],
    requestLedger: [],
    retentionError: "",
    retentionLastRun: null,
    retentionLoading: false,
    retentionRuns: [],
    retentionSubsystems: "",
    rotateAPIKeyID: "",
    rotateAPIKeySecret: "",
    runtimeHeaders: null,
    chatSessionsHasMore: false,
    chatSessionsLoadingMore: false,
    tenant: "",
    tenantFormID: "",
    tenantFormModels: [],
    tenantFormName: "",
    tenantFormProviders: [],
    tenantFormSystemPrompt: "",
    visibleModels: [],
    ...overrides,
  };
}

export function createRuntimeConsoleActions(): RuntimeConsoleViewModel["actions"] {
  return {
    copyCommand: async () => undefined,
    createChatSession: async () => undefined,
    deleteChatSession: async () => undefined,
    deleteAPIKey: async () => undefined,
    deletePolicyRule: async () => undefined,
    deleteTenant: async () => undefined,
    loadDashboard: async () => undefined,
    resetBudget: async () => undefined,
    rotateAPIKey: async () => undefined,
    renameChatSession: async () => undefined,
    setAPIKeyEnabled: async () => undefined,
    setAPIKeyFormID: () => undefined,
    setAPIKeyFormModels: () => undefined,
    setAPIKeyFormName: () => undefined,
    setAPIKeyFormProviders: () => undefined,
    setAPIKeyFormRole: () => undefined,
    setAPIKeyFormSecret: () => undefined,
    setAPIKeyFormTenant: () => undefined,
    setAuthToken: () => undefined,
    setBudgetAmountUsd: () => undefined,
    setBudgetLimitUsd: () => undefined,
    setMessage: () => undefined,
    setSystemPrompt: () => undefined,
    setModel: () => undefined,
    setModelFilter: () => undefined,
    setProviderFilter: () => undefined,
    refreshProviders: async () => undefined,
    setRetentionSubsystems: () => undefined,
    setRotateAPIKeyID: () => undefined,
    setRotateAPIKeySecret: () => undefined,
    setTenantEnabled: async () => undefined,
    setTenant: () => undefined,
    setTenantFormID: () => undefined,
    setTenantFormModels: () => undefined,
    setTenantFormName: () => undefined,
    setTenantFormProviders: () => undefined,
    setTenantFormSystemPrompt: () => undefined,
    setBudgetLimit: async () => undefined,
    submitChat: async () => undefined,
    submitToolResults: async () => undefined,
    runRetention: async () => undefined,
    loadMoreChatSessions: async () => undefined,
    selectChatSession: async () => undefined,
    startNewChat: () => undefined,
    topUpBudget: async () => undefined,
    upsertAPIKey: async () => undefined,
    upsertPolicyRule: async () => undefined,
    upsertTenant: async () => undefined,
    updateToolResult: () => undefined,
    clearAuthToken: () => undefined,
    setProviderAPIKey: async () => undefined,
    createProvider: async () => undefined,
    deleteProvider: async () => undefined,
    setProviderBaseURL: async () => undefined,
    setProviderName: async () => undefined,
    setProviderCustomName: async () => undefined,
    upsertPricebookEntry: async () => undefined,
    deletePricebookEntry: async () => undefined,
    previewPricebookImport: async () => ({ fetched_at: "", unchanged: 0 }),
    applyPricebookImport: async () => ({ fetched_at: "", unchanged: 0 }),
    dismissNotice: () => undefined,
  };
}
