import type { RuntimeConsoleViewModel } from "../app/useRuntimeConsole";

export function createRuntimeConsoleFixture(
  overrides: Partial<RuntimeConsoleViewModel["state"]> = {},
): RuntimeConsoleViewModel["state"] {
  return {
    apiKeyFormID: "",
    apiKeyFormModels: "",
    apiKeyFormName: "",
    apiKeyFormProviders: "",
    apiKeyFormRole: "tenant",
    apiKeyFormSecret: "",
    apiKeyFormTenant: "",
    authToken: "",
    accountSummary: null,
    budget: null,
    budgetActionError: "",
    budgetAmountUsd: "1.00",
    budgetLimitUsd: "5.00",
    activeChatSession: null,
    activeChatSessionID: "",
    chatError: "",
    chatLoading: false,
    streamingContent: null,
    chatResult: null,
    pendingToolCalls: [],
    chatSessions: [],
    cloudModels: [],
    cloudProviders: [],
    controlPlane: null,
    controlPlaneError: "",
    copiedCommand: "",
    error: "",
    health: { status: "ok", time: "2026-04-21T10:00:00Z" },
    healthyCloudProviders: 0,
    healthyLocalProviders: 0,
    healthyProviders: 0,
    loading: false,
    localModels: [],
    localProviderIssues: [],
    localProviders: [],
    message: "Say hello",
    model: "gpt-4o-mini",
    modelFilter: "all",
    models: [],
    notice: null,
    session: {
      kind: "anonymous",
      label: "Anonymous",
      capabilities: [],
      isAdmin: false,
      isAuthenticated: false,
      role: "anonymous",
      name: "",
      tenant: "",
      source: "",
      keyID: "",
      allowedProviders: [],
      allowedModels: [],
    },
    providerFilter: "auto",
    providerFormAPIVersion: "",
    providerFormAllowAnyModel: "true",
    providerFormBaseURL: "",
    providerFormDefaultModel: "",
    providerFormEnabled: "true",
    providerFormID: "",
    providerFormKind: "cloud",
    providerFormModels: "",
    providerFormName: "",
    providerFormPresetID: "",
    providerFormProtocol: "openai",
    providerFormSecret: "",
    providerPresets: [],
    providerScopedModels: [],
    providers: [],
    rotateProviderID: "",
    rotateProviderSecret: "",
    requestLedger: [],
    retentionError: "",
    retentionLastRun: null,
    retentionLoading: false,
    retentionRuns: [],
    retentionSubsystems: "",
    rotateAPIKeyID: "",
    rotateAPIKeySecret: "",
    runtimeHeaders: null,
    traceError: "",
    traceRoute: null,
    traceSpans: [],
    traceLoading: false,
    traceStartedAt: "",
    tenant: "team-a",
    tenantFormID: "",
    tenantFormModels: "",
    tenantFormName: "",
    tenantFormProviders: "",
    visibleModels: [],
    ...overrides,
  };
}

export function createRuntimeConsoleActions(): RuntimeConsoleViewModel["actions"] {
  return {
    copyCommand: async () => undefined,
    createChatSession: async () => undefined,
    deleteChatSession: async () => undefined,
    deleteAPIKey: async () => undefined,
    deleteProvider: async () => undefined,
    deleteTenant: async () => undefined,
    loadDashboard: async () => undefined,
    resetBudget: async () => undefined,
    rotateAPIKey: async () => undefined,
    rotateProviderCredential: async () => undefined,
    renameChatSession: async () => undefined,
    setAPIKeyEnabled: async () => undefined,
    setAPIKeyFormID: () => undefined,
    setAPIKeyFormModels: () => undefined,
    setAPIKeyFormName: () => undefined,
    setAPIKeyFormProviders: () => undefined,
    setAPIKeyFormRole: () => undefined,
    setAPIKeyFormSecret: () => undefined,
    setAPIKeyFormTenant: () => undefined,
    setAuthToken: () => undefined,
    setBudgetAmountUsd: () => undefined,
    setBudgetLimitUsd: () => undefined,
    setMessage: () => undefined,
    setModel: () => undefined,
    setModelFilter: () => undefined,
    setProviderFilter: () => undefined,
    setProviderEnabled: async () => undefined,
    setProviderFormAPIVersion: () => undefined,
    setProviderFormAllowAnyModel: () => undefined,
    setProviderFormBaseURL: () => undefined,
    setProviderFormDefaultModel: () => undefined,
    setProviderFormEnabled: () => undefined,
    setProviderFormID: () => undefined,
    setProviderFormKind: () => undefined,
    setProviderFormModels: () => undefined,
    setProviderFormName: () => undefined,
    setProviderFormPresetID: () => undefined,
    setProviderFormProtocol: () => undefined,
    setProviderFormSecret: () => undefined,
    setRetentionSubsystems: () => undefined,
    setRotateAPIKeyID: () => undefined,
    setRotateAPIKeySecret: () => undefined,
    setRotateProviderID: () => undefined,
    setRotateProviderSecret: () => undefined,
    setTenantEnabled: async () => undefined,
    setTenant: () => undefined,
    setTenantFormID: () => undefined,
    setTenantFormModels: () => undefined,
    setTenantFormName: () => undefined,
    setTenantFormProviders: () => undefined,
    setBudgetLimit: async () => undefined,
    submitChat: async () => undefined,
    runRetention: async () => undefined,
    selectChatSession: async () => undefined,
    populateProviderFormFromPreset: () => undefined,
    startNewChat: () => undefined,
    topUpBudget: async () => undefined,
    upsertAPIKey: async () => undefined,
    upsertProvider: async () => undefined,
    upsertTenant: async () => undefined,
    clearAuthToken: () => undefined,
    dismissNotice: () => undefined,
  };
}
